INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('00001', 'Sophia Smith', NULL);
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('00010', 'Emma Johnson', NULL);
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('00011', 'Isabella Williams', NULL);
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('00100', 'Jacob Brown', NULL);
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('00101', 'Mason Jones', NULL);
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('00110', 'Ethan Miller', NULL);
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('00111', 'Noah Davis', NULL);
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('01000', 'Olivia Garcia', NULL);
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('01001', 'William Rodriguez', NULL);
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('01010', 'Liam Wilson', NULL);
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('01011', 'Jayden Martinez', NULL);
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('01100', 'Michael Anderson', NULL);
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('01101', 'Ava Taylor', NULL);
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('01110', 'Alexander Thomas', NULL);
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('01111', 'Aiden Hernandez', NULL);
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('10000', 'Daniel Moore', NULL);
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('10001', 'Matthew Martin', NULL);
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('10010', 'Elijah Jackson', NULL);
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('10011', 'Emily Thompson', NULL);
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('10100', 'James White', NULL);

INSERT INTO Puesto (pst_id, pst_nombre) VALUES ('00001', 'Puesto 1');
INSERT INTO Puesto (pst_id, pst_nombre) VALUES ('00002', 'Puesto 2');
INSERT INTO Puesto (pst_id, pst_nombre) VALUES ('00003', 'Puesto 3');
INSERT INTO Puesto (pst_id, pst_nombre) VALUES ('00004', 'Puesto 4');
INSERT INTO Puesto (pst_id, pst_nombre) VALUES ('00005', 'Puesto 5');
INSERT INTO Puesto (pst_id, pst_nombre) VALUES ('00006', 'Puesto 6');
INSERT INTO Puesto (pst_id, pst_nombre) VALUES ('00007', 'Puesto 7');
INSERT INTO Puesto (pst_id, pst_nombre) VALUES ('00008', 'Puesto 8');
INSERT INTO Puesto (pst_id, pst_nombre) VALUES ('00009', 'Puesto 9');
INSERT INTO Puesto (pst_id, pst_nombre) VALUES ('00010', 'Puesto 10');
INSERT INTO Puesto (pst_id, pst_nombre) VALUES ('00011', 'Puesto 11');
INSERT INTO Puesto (pst_id, pst_nombre) VALUES ('00012', 'Puesto 12');

INSERT INTO Capacidad(cap_nombre,cap_puesto,cap_empleado)VALUES(NULL,'00001','00001');
INSERT INTO Capacidad(cap_nombre,cap_puesto,cap_empleado)VALUES(NULL,'00002','00010');
INSERT INTO Capacidad(cap_nombre,cap_puesto,cap_empleado)VALUES(NULL,'00003','00011');
INSERT INTO Capacidad(cap_nombre,cap_puesto,cap_empleado)VALUES(NULL,'00004','00100');
INSERT INTO Capacidad(cap_nombre,cap_puesto,cap_empleado)VALUES(NULL,'00005','00101');
INSERT INTO Capacidad(cap_nombre,cap_puesto,cap_empleado)VALUES(NULL,'00006','00110');
INSERT INTO Capacidad(cap_nombre,cap_puesto,cap_empleado)VALUES(NULL,'00007','00111');
INSERT INTO Capacidad(cap_nombre,cap_puesto,cap_empleado)VALUES(NULL,'00008','01000');
INSERT INTO Capacidad(cap_nombre,cap_puesto,cap_empleado)VALUES(NULL,'00003','00111');