INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('99880','Gonzalez Sanchez Rosa Maria','18sa0051');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9A2AJ','Castañeda Salas Pedro','18sa0211');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9A2FL','Alvarado De La Cerda Gilberto','18ca0028');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9A2FP','Saenz Ramirez Sergio','18ca0011');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9A2G4','Reyes Vaquero Simitrio','18ca0030');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9A2GC','Rodriguez Garcia Hector','18ca0019');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9A2GU','Zamarron Fraga Javier','18ca0025');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9AAMJ','Sandoval Rodriguez Ernesto','18sa0155');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9AAMK','De Luna Saldivar Arturo','18ca0002');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9AAML','Huerta Rivera Anselmo','18sa0159');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9AAMM','Narvaez Plascencia Armando','18sa0005');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9AAMN','Sandoval Rodriguez Raul','18sa0156');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9AAMP','Acosta Luna Gerardo','18sa0165');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9AAN4','Pimentel Mora Edgar Gerardo','18sa0167');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9AAN5','Martinez Zepeda Jose Humberto','18sa0193');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9AANA','Olvera Terrazas Jorge Rodolfo','18sa0082');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9AANC','Garcia Saenz Humberto Bulmaro','18sa0085');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9AANE','Elizundia Alvarez Ricardo Antonio','18sa0096');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9AANG','Muñiz Valades Mario','18sa0083');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9AANH','Reza Castro Jose Rafael','18sa0084');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9AANJ','Jaime Luna Salvador','18sa0114');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9AANK','Galvan Olvera Agustin','18sa0066');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9AANN','Martinez Luna Jose Artemio','18sa0200');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9AANT','Sandoval Pimentel Lorena','18sa0147');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9AAP4','Sandoval Marquez Ricardo','18sa0168');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9AAT3','Saldivar Gonzalez Othoniel Oswaldo','18sa0062');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9AATC','Sanchez Balderas Jesus Alberto','18sa0097');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9AATK','Vitela Rodriguez Jose','18ca0004');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9AAU0','Hernandez Lara Joaquin Albino','18sa0145');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9AAU6','Roman Alonso Carlos Mauricio','18ca0007');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9AAVE','Noyola Gaytan Alfonso','18sa0161');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9AAVH','Ortega Juarez Rodrigo','18sa0135');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9AAW1','Pinera Zuñiga Luis Fernando','18sa0091');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9AAW3','Basurto Sandoval Carlos','18sa0162');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9AAW6','Rodriguez Santos Abelardo','18sa0166');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9AAW7','Domingo Sandoval Victor Manuel','18sa0171');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9AAWD','Alvarado Ortiz Francisco','18sa0148');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9AAWV','Gajon Elydd Jesus','18sa0157');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9AAWW','Arroyo Lopez Maria Del Rosario','18sa0067');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9AAWY','Ruiz Valdez Joaquin','18sa0057');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9AAXN','Raigosa Garcia Jose Adan','18ca0021');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9AAYD','Garcia Rivera Omar','18ca0005');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9AAYF','Ortega Ibarra Norma Patricia','18sa0144');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9AAYJ','Ceniceros Goitia Jesus','18sa0059');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9AAYL','Rubio Calderon Jesus Antonio','18sa0177');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9AAYN','Mora Gonzalez Veronica','18sa0197');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9AB0H','Posada Walle Victor Manuel','18sa0164');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9AB0T','Acosta Cervantes Oscar Rene','18sa0101');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9AB14','Ibarra Medina Jaime','18sa0158');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9AB2H','Diaz Perez Jose Antonio','18sa0088');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9AB2K','Lopez Franco Santiago','18sa0134');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9AB2M','Montanez Duran Jose Angel','18sa0105');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9AD9R','Gil Raya Ernesto','18sa0121');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9AD9T','Valdes Jimenez Fernando','18sa0086');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9ADA6','Silva Posada Roberto','18sa0163');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9ADAN','Cuevas Hinojosa Jose Cristobal','18sa0124');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9ADAT','Sanchez Uranga Hector Manuel','18sa0160');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9AG1G','Herrera Acevedo Jose Bernardo','18sa0118');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9AG1J','Rodriguez Garcia Sergio','18sa0117');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9AG1K','Peralta Rada Jesus','18sa0069');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9AG2L','Rivera Llanes Jose Santos','18sa0120');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9AG67','Martinez Zepeda Diana','18sa0142');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9AG82','Garcia Pichardo Vicente','18sa0103');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9AG83','Silva Duran Jesus','18sa0070');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9AG8K','Castorena Macias Ruben','18sa0065');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9AG8P','Ayala Garay Juan Manuel','18ca0026');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9AGA8','Astorga Dominguez Raul Alfredo','18sa0130');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9AGAA','Esparza Avila Gonzalo','18sa0060');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9AGAW','Leyva Aldama Fernando','18sa0169');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9AGBW','Gallardo Martinez Ernesto','18ca0031');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9AGC1','Moran Cadena Jose Carlos','18sa0173');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9AGDB','Contreras Flores Humberto','18sa0182');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9AGDC','Ramirez Muñoz Gerardo','18sa0190');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9APBN','Rodriguez Herrera Jose Luis','18sa0138');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9APBR','Sandoval Hernandez Heriberto','18sa0111');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9APHA','Lopez Echavarri Carlos Augusto','18sa0098');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9APLG','Nuñez Arambula Juan Carlos','18sa0061');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9APLP','Sornia Lira Guillermo Gerardo','18sa0201');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9APLQ','Contreras Astorga Enrique','18sa0068');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9APLR','Luevanos Espinoza Oscar Margarito','18sa0176');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9APLS','Huerta Felix Felipe De Jesus','18sa0106');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9B34R','Rodriguez Alanis Maria De Lourdes','18ca0014');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9B3A6','Saenz Corral Victor Manuel','18ca0020');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9B3A9','Valadez Vicencio Martin Armando','18ca0027');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9B3BA','Alvarez Cardenas Manuel','18ca0001');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9B3FC','Fernandez Villarreal Vladimir','18ca0022');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9B3H0','Rodriguez Rivera Andres','18sa0172');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9B3HW','Martinez Cabral Luis','18sa0063');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9B3J5','Alvarado Avalos Porfirio','18sa0104');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9B3J6','Monsivais Nava Carlos Brigido','18sa0195');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9B3J8','Castañeda Salas Juan Gerardo','18sa0127');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9B3J9','Garcia Prieto Jose Antonio','18sa0090');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9B3JA','Reyes Manriquez Andres Eduardo','18sa0198');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9B3LH','Salas Garcia Andres Javier','18sa0186');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9B3LJ','Huerta Sanchez Jose David','18sa0131');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9B3LL','Frayre Nuñez Juan Antonio','18sa0094');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9B3LT','Lopez Martinez Oscar','18sa0199');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9B9N9','Martinez Acosta Gerardo','18ca0008');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9B9R0','Morales Cisneros Geronimo','18sa0183');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9B9R1','Juarez Montes Jesus','18sa0087');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9B9R2','Hernandez Orozco Roberto','18sa0064');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9B9RP','Alvarado Arguijo Gerardo','18sa0153');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9B9RR','Huerta Rivera Sergio','18sa0092');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9B9RT','Monsivais Jimenez Jose Luis','18sa0151');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9B9TJ','Carrillo Adame Ronaldo De Jesus','18sa0100');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9BA2W','Ruiz Valdez Fabian','18sa0179');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9BA2X','Vallejo Contreras Oscar','18sa0191');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9BA3N','Gonzalez Bustamante Reynaldo Javier','18sa0099');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9BA62','Hernandez Castañeda Juan Francisco','18sa0126');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9BA63','Mcvey Puentes Paloma De Maria','18ca0012');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9BA72','Alvarez Luna Jose Luis','18sa0196');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9BA73','De La Torre Rangel Josue Carlos','18sa0102');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9BA74','Mora Lopez Francisco Javier','18sa0202');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9BA7A','Sandoval Marquez Bernardo Alonso','18sa0184');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9BA7J','Naranjo Torres Rosa Elia','18sa0140');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9BA7X','Garcia Martinez Laura Mercedes','18ca0017');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9ERJF','Muñoz Montañez Francisco Javier','18sa0188');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9ERJM','Fernandez Fernandez Maria Soledad','18sa0146');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9ERKT','Posada Medina Antonio','18sa0174');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9ERMW','Sanchez Arevalo Carlos','18ca0023');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9ERNN','Martinez Ibarra Hugo Heriberto','18sa0189');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9L8TM','Flores Duarte Aldo Hiram','18ca0006');

INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9AAN2','Navarro Hernandez Jose Antonio','');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9AAXA','Monsivais Nava Jose Luis','');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9ERN1','Becerra Alanis Jorge Humberto','');
INSERT INTO Empleado (emp_id,emp_nombre,emp_puesto) VALUES ('9ERRT','Arroyo Lopez Juan Antonio','');