INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18ca0001','Supervisor Tecnico II');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18ca0002','Jefe Departamento Tecnico II');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18ca0004','Superintendente Turno II');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18ca0005','Superintendente Turno II');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18ca0006','Superintendente Turno II');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18ca0007','Superintendente Turno II');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18ca0008','Jefe Departamento Tecnico II');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18ca0011','Superintendente Central II');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18ca0012','Secretaria');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18ca0014','Jefe Departamento Tecnico II');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18ca0017','Jefe Departamento Tecnico II');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18ca0019','Jefe Departamento Tecnico II');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18ca0020','Supervisor Tecnico II');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18ca0021','Supervisor Tecnico II');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18ca0022','Jefe Departamento Tecnico II');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18ca0023','Supervisor Tecnico II');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18ca0025','Jefe Departamento Tecnico II');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18ca0026','Administrador Central II');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18ca0027','Supervisor Administrativo II');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18ca0028','Supervisor Administrativo II');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18ca0030','Supervisor Administrativo II');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18ca0031','Supervisor Administrativo II');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0005','Tecnico Superior');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0051','Oficinista');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0057','Jefe Mantenimiento');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0059','Tecnico Superior');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0060','Tecnico');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0061','Tecnico');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0062','Ayudante Tecnico');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0063','Ayudante Tecnico');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0064','Ayudante Tecnico');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0065','Ayudante Tecnico');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0066','Chofer Operador Equipo');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0067','Oficinista');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0068','Tecnico Superior');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0069','Tecnico Superior');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0070','Tecnico Superior');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0082','Jefe Mantenimiento');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0083','Tecnico Superior');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0084','Tecnico Superior');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0085','Tecnico Superior');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0086','Tecnico');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0087','Tecnico');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0088','Tecnico');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0090','Tecnico');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0091','Tecnico');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0092','Tecnico');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0094','Ayudante Tecnico');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0096','Ayudante Tecnico');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0097','Ayudante Tecnico');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0098','Ayudante Tecnico');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0099','Ayudante Tecnico');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0100','Ayudante Tecnico');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0101','Ayudante Tecnico');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0102','Ayudante Tecnico');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0103','Ayudante Tecnico');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0104','Auxiliar Mantenimiento');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0105','Auxiliar Mantenimiento');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0106','Auxiliar Mantenimiento');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0111','Auxiliar Servicios I');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0114','Tecnico Superior');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0117','Tecnico Superior');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0118','Tecnico Superior');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0120','Tecnico Superior');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0121','Tecnico Superior');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0124','Ayudante Tecnico');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0126','Ayudante Tecnico');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0127','Ayudante Tecnico');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0130','Ayudante Tecnico');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0131','Ayudante Tecnico');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0134','Tecnico');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0135','Tecnico');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0138','Auxiliar Servicios Chofer');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0140','Auxiliar Administrativo');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0142','Oficinista');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0144','Auxiliar Administrativo');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0145','Auxiliar Administrativo');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0146','Oficinista');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0147','Auxiliar Administrativo');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0148','Oficinista');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0151','Auxiliar Servicios I');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0153','Oficinista');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0155','Operador Central II');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0156','Operador Central II');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0157','Operador Central II');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0158','Operador Central II');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0159','Operador Central II');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0160','Operador Central II');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0161','Operador Central II');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0162','Operador Central II');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0163','Auxiliar Operacion II');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0164','Auxiliar Operacion II');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0165','Auxiliar Operacion II');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0166','Auxiliar Operacion II');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0167','Fogonero II');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0168','Fogonero II');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0169','Fogonero II');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0171','Fogonero II');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0172','Fogonero II');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0173','Fogonero II');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0174','Fogonero II');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0176','Patiero II');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0177','Patiero II');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0179','Patiero II');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0182','Patiero II');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0183','Auxiliar Servicios Operacion');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0184','Auxiliar Servicios Operacion');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0186','Auxiliar Servicios Operacion');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0188','Auxiliar Servicios Operacion');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0189','Auxiliar Servicios Operacion');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0190','Auxiliar Servicios Operacion');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0191','Auxiliar Servicios Operacion');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0193','Auxiliar Servicios Operacion');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0195','Ayudante Operacion II');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0196','Ayudante Operacion II');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0197','Ayudante Operacion II');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0198','Ayudante Operacion II');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0199','Patiero II');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0200','Patiero II');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0201','Patiero II');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0202','Patiero II');
INSERT INTO Puesto (pst_id,pst_nombre) VALUES ('18sa0211','Ayudante Operacion II');

INSERT INTO Puesto (pst_id, pst_nombre) VALUES ('', 'Fogonero II');
INSERT INTO Puesto (pst_id, pst_nombre) VALUES ('', 'Patiero II');
INSERT INTO Puesto (pst_id, pst_nombre) VALUES ('', 'Auxiliar Servicios Operacion');